### ISSUE TITLE
Future events aren't handled nicely

### ISSUE THREAD

**Issue by alertedsnake** [jwplayer/rssalertbot#9]
If there's a future event in a feed, it's assumed to be the newest event and thus other events that come in before that event will be ignored.

A possible solution would be to just ignore future events entirely until they're past events... but perhaps one might want to be alerted about future events in some way?  We'd have to prevent them from being alerted more than once also, so the date isn't going to be the best marker.

**Comment by mgundel** [comment]
Fixed by https://github.com/jwplayer/rssalertbot/pull/10
